main:
  - name: About Me
    url: /about_me/
    weight: 10
  - name: Company Interviews
    url: publication/
    weight: 11
  - name: Interests
    url: interests/
    identifier: interests
    weight: 12
  - name: Climbing
    url: interest/climbing/
    parent: interests
    weight: 13
  - name: Running
    url: interest/running/
    parent: interests
    weight: 14
  - name: Hiking
    url: interest/hiking/
    parent: interests
    weight: 15
  - name: Travel
    url: interest/travel/
    parent: interests
    weight: 16
  - name: Projects
    url: project/
    identifier: projects
    weight: 30
  - name: Geospatial Information
    url: project/geospatial-information/
    parent: projects
    weight: 31
  - name: Legal AI Advisor
    url: project/legal-ai-advisor/
    parent: projects
    weight: 32
  - name: Embedded
    url: project/embedded/
    parent: projects
    weight: 33
  - name: Habit Tracker App
    url: project/habit-tracker/
    parent: projects
    weight: 34
  - name: Contact
    url: contact/
    weight: 40
