main:
  - name: AboutMe
    url: /about_me/
    weight: 10
  - name: Interview
    url: /#papers
    weight: 11
  - name: Interest
    url: interests/
    identifier: interests
    weight: 12
  - name: Climbing
    url: interest/클라이밍/
    parent: interests
    weight: 13
  - name: Running
    url: interest/러닝/
    parent: interests
    weight: 14
  - name: Hiking
    url: interest/등산/
    parent: interests
    weight: 15
  - name: Travel
    url: interest/여행/
    parent: interests
    weight: 16
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects  # 상위 메뉴로 작동
    url: project/
    identifier: projects
    weight: 30
  - name: 공간정보
    url: project/공간정보/
    parent: projects  # 'Projects'의 하위 메뉴
    weight: 31
  - name: 변호에몽
    url: project/변호에몽/
    parent: projects
    weight: 32
  - name: 날씨알리미
    url: project/임베디드/
    parent: projects
    weight: 33
  - name: 탕후루틴
    url: project/탕후루틴/
    parent: projects
    weight: 34  # 이 부분이 다른 weight와 중복되었으므로 수정
  - name: Contact
    url: contact/
    weight: 40
