main:
  - name: Tour
    url: /tour
    weight: 10
  - name: Interview
    url: /#papers
    weight: 11
  - name: Interest
    url: interests/
    identifier: interests
    weight: 12
  - name: Climbing
    url: interest/클라이밍/
    parent: interests  # 수정: 'interest' -> 'interests'
    weight: 13
  - name: Running
    url: interest/러닝/
    parent: interests  # 수정: 'interest' -> 'interests'
    weight: 14
  - name: Hiking
    url: interest/등산/
    parent: interests  # 수정: 'interest' -> 'interests'
    weight: 15
  - name: Travel
    url: interest/여행/
    parent: interests  # 수정: 'interest' -> 'interests'
    weight: 16
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    identifier: projects
    weight: 30
  - name: 공간정보
    url: project/공간정보/
    parent: projects
    weight: 31
  - name: 변호에몽
    url: project/변호에몽/
    parent: projects
    weight: 32
  - name: Contact
    url: contact/
    weight: 40
